DROP TABLE bills;
DROP TABLE subscription_history;
DROP TABLE requests;
DROP TABLE subscriptions;
DROP TABLE packages;
DROP TABLE users;

CREATE TABLE users(
    id NUMBER(10)  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50),
    email VARCHAR2(50) UNIQUE,
    password VARCHAR2(200),
    role VARCHAR2(10) DEFAULT 'customer' CHECK(role IN('admin', 'customer')),
    remember_token VARCHAR2(100)
);
CREATE TABLE packages(
    package_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_name VARCHAR2(50) UNIQUE,
    download_speed NUMBER(10),
    upload_speed NUMBER(10),
    connection_type VARCHAR2(10) CHECK (connection_type IN ('fiber', 'wireless', 'copper')),
    ip_type VARCHAR2(10) CHECK (ip_type IN ('shared', 'dedicated')),
    price NUMBER(10,2)
);
CREATE TABLE subscriptions(
    subscription_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(10),
    package_id NUMBER(10),
    status VARCHAR2(15) DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (package_id) REFERENCES packages(package_id) ON DELETE CASCADE
);
CREATE TABLE requests(
    request_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(10),
    subscription_id NUMBER(10),
    new_package_id NUMBER(10),
    request_type VARCHAR2(20) CHECK (request_type IN ('new', 'change', 'unsubscribe')),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (new_package_id) REFERENCES packages(package_id) ON DELETE CASCADE
);
CREATE TABLE subscription_history(
    history_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(10),
    old_package_id NUMBER(10),
    new_package_id NUMBER(10),
    type VARCHAR2(20) CHECK (type IN ('new', 'change', 'unsubscribe')),
    processed_at DATE DEFAULT SYSDATE
);
CREATE TABLE bills(
    user_id NUMBER(10) PRIMARY KEY,
    subscription_count NUMBER(10) DEFAULT 0,
    total_cost NUMBER(10,2) DEFAULT 0,
    discount NUMBER(10,2) DEFAULT 0,
    net_bill NUMBER(10,2) DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE OR REPLACE PROCEDURE approve_request( p_request_id IN NUMBER) AS
    v_user_id users.id%TYPE;
    v_subscription_id subscriptions.subscription_id%TYPE;
    v_new_package_id packages.package_id%TYPE;
    v_request_type requests.request_type%TYPE;
BEGIN
    SELECT user_id,subscription_id, new_package_id, request_type
    INTO v_user_id, v_subscription_id, v_new_package_id, v_request_type
    FROM requests WHERE request_id = p_request_id;   

    IF v_request_type = 'new' THEN
        INSERT INTO subscriptions(user_id, package_id, status) VALUES(v_user_id, v_new_package_id, 'active');

    ELSIF v_request_type = 'change' THEN
        UPDATE subscriptions SET package_id = v_new_package_id WHERE subscription_id = v_subscription_id;

    ELSIF v_request_type = 'unsubscribe' THEN
        DELETE FROM subscriptions WHERE subscription_id = v_subscription_id;

    END IF;

    DELETE FROM requests WHERE request_id = p_request_id;

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;

END approve_request;
/

CREATE OR REPLACE TRIGGER log_subscription_change AFTER INSERT OR UPDATE OR DELETE ON subscriptions
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO subscription_history (user_id, old_package_id, new_package_id, type, processed_at)
        VALUES (:NEW.user_id, NULL, :NEW.package_id, 'new', SYSDATE);
    ELSIF UPDATING THEN
        INSERT INTO subscription_history (user_id, old_package_id, new_package_id, type, processed_at)
        VALUES (:NEW.user_id, :OLD.package_id, :NEW.package_id, 'change', SYSDATE);
    ELSIF DELETING THEN
        INSERT INTO subscription_history (user_id, old_package_id, new_package_id, type, processed_at)
        VALUES (:OLD.user_id, :OLD.package_id, NULL, 'unsubscribe', SYSDATE);
    END IF;
END;
/

CREATE OR REPLACE FUNCTION get_discount_rate( p_subscription_count IN NUMBER)
RETURN NUMBER AS
BEGIN
    IF p_subscription_count = 2 THEN
        RETURN 0.05;
    ELSIF p_subscription_count = 3 THEN
        RETURN 0.10;
    ELSIF p_subscription_count >= 4 THEN
        RETURN 0.20;
    ELSE
        RETURN 0;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER update_bill FOR INSERT OR UPDATE OR DELETE ON subscriptions
COMPOUND TRIGGER

    TYPE t_user_ids IS TABLE OF NUMBER;
    v_user_ids t_user_ids := t_user_ids();
    v_index INTEGER := 0;

    AFTER EACH ROW IS
    BEGIN
        v_index := v_index + 1;
        v_user_ids.EXTEND;
        IF INSERTING OR UPDATING THEN
            v_user_ids(v_index) := :NEW.user_id;
        ELSE
            v_user_ids(v_index) := :OLD.user_id;
        END IF;
    END AFTER EACH ROW;

    AFTER STATEMENT IS
        v_subscription_count NUMBER;
        v_total_cost NUMBER;
        v_discount_rate NUMBER;
        v_discount NUMBER;
        v_net_bill NUMBER;
    BEGIN
        FOR i IN 1 .. v_user_ids.COUNT LOOP
            SELECT COUNT(*), NVL(SUM(p.price),0) INTO v_subscription_count, v_total_cost
            FROM subscriptions s JOIN packages p ON s.package_id = p.package_id
            WHERE s.user_id = v_user_ids(i);

            v_discount_rate := get_discount_rate(v_subscription_count);
            v_discount := v_total_cost * v_discount_rate;
            v_net_bill := v_total_cost - v_discount;

            UPDATE bills SET
                subscription_count = v_subscription_count,
                total_cost = v_total_cost,
                discount = v_discount,
                net_bill = v_net_bill
            WHERE user_id = v_user_ids(i);

            IF SQL%ROWCOUNT = 0 THEN
                INSERT INTO bills( user_id, subscription_count, total_cost, discount, net_bill)
                VALUES( v_user_ids(i), v_subscription_count, v_total_cost, v_discount, v_net_bill);
            END IF;
        END LOOP;
    END AFTER STATEMENT;
END update_bill;
/

