DROP TABLE requests CASCADE CONSTRAINTS;
DROP TABLE subscriptions CASCADE CONSTRAINTS;
DROP TABLE packages CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;

CREATE TABLE users(
    id NUMBER(10)  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    email VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(200) NOT NULL,
    role VARCHAR2(10) CHECK(role IN('admin', 'customer')) NOT NULL,
    remember_token VARCHAR2(100)
);
CREATE TABLE packages(
    package_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_name VARCHAR2(50) NOT NULL UNIQUE,
    download_speed NUMBER(10) NOT NULL,
    upload_speed NUMBER(10) NOT NULL,
    connection_type VARCHAR2(10) NOT NULL CHECK (connection_type IN ('fiber', 'wireless', 'copper')),
    ip_type VARCHAR2(10) NOT NULL CHECK (ip_type IN ('shared', 'dedicated')),
    price NUMBER(10,2) NOT NULL
);
CREATE TABLE subscriptions(
    subscription_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(10) NOT NULL,
    package_id NUMBER(10) NOT NULL,
    status VARCHAR2(15) CHECK (status IN ('active', 'inactive')) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (package_id) REFERENCES packages(package_id)
);
CREATE TABLE requests(
    request_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(10) NOT NULL,
    subscription_id NUMBER(10),
    current_package_id NUMBER(10),
    new_package_id NUMBER(10),
    request_type VARCHAR2(20) CHECK (request_type IN ('new', 'change', 'unsubscribe')) NOT NULL,
    status VARCHAR2(20) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (current_package_id) REFERENCES packages(package_id),
    FOREIGN KEY (new_package_id) REFERENCES packages(package_id)
);

