<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::statement("
            CREATE TABLE users(
                id NUMBER(10)  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(50) NOT NULL,
                email VARCHAR2(50) UNIQUE NOT NULL,
                password VARCHAR2(200) NOT NULL,
                role VARCHAR2(10) CHECK(role IN('admin', 'customer')) NOT NULL,
                remember_token VARCHAR2(100)
            )
        ");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::statement("DROP TABLE users CASCADE CONSTRAINTS");
    }
};
