<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::statement("
            CREATE TABLE requests(
                request_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id NUMBER(10) NOT NULL,
                subscription_id NUMBER(10),
                new_package_id NUMBER(10),
                request_type VARCHAR2(20) CHECK (request_type IN ('new', 'change', 'unsubscribe')) NOT NULL,
                FOREIGN KEY (user_id) REFERENCES users(id),
                FOREIGN KEY (subscription_id) REFERENCES subscriptions(subscription_id),
                FOREIGN KEY (new_package_id) REFERENCES packages(package_id)
            )
        ");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::statement("DROP TABLE requests CASCADE CONSTRAINTS");
    }
};
