<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::statement("
            CREATE TABLE packages(
                package_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                package_name VARCHAR2(50) NOT NULL UNIQUE,
                download_speed NUMBER(10) NOT NULL,
                upload_speed NUMBER(10) NOT NULL,
                connection_type VARCHAR2(10) NOT NULL CHECK (connection_type IN ('fiber', 'wireless', 'copper')),
                ip_type VARCHAR2(10) NOT NULL CHECK (ip_type IN ('shared', 'dedicated')),
                price NUMBER(10,2) NOT NULL
            )
        ");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::statement("DROP TABLE packages CASCADE CONSTRAINTS");
    }
};
