<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::statement("
            CREATE TABLE subscriptions(
                subscription_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id NUMBER(10) NOT NULL,
                package_id NUMBER(10) NOT NULL,
                status VARCHAR2(15) CHECK (status IN ('active', 'inactive')) NOT NULL,
                FOREIGN KEY (user_id) REFERENCES users(id),
                FOREIGN KEY (package_id) REFERENCES packages(package_id)
            )
        ");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::statement("DROP TABLE subscriptions CASCADE CONSTRAINTS");
    }
};
